#
# From https://github.com/isamadrid90/gradle-pitest-comment-action/blob/main/action.yml
#
name: PITest
on:
  pull_request:

jobs:
  pitest:
    runs-on: ubuntu-latest
    name: PITest
    steps:
      - name: ğŸ— Checkout
        uses: actions/checkout@v3
      - uses: isamadrid90/gradle-pitest-comment-action@v1.0.0-beta
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          reports-retention: 1
          reports-path: "ran-core/build/reports/pitest"
          working-directory: project
